### PR TITLE
create common functions to make code more readable

### PR DESCRIPTION
**Pull request by chengxiangdong**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chengxiangdong** [comment]
Lint check has a bug, I will fix it in another PR.

**Comment by niuzhenguo** [comment]
@chengxiangdong pls resolve the conflicts first.

**Comment by chengxiangdong** [comment]
> @chengxiangdong pls resolve the conflicts first.

@niuzhenguo the code has been rebased, pls review again

**Pull request merged**
