### PR TITLE
Updated all docs and replace huawei-cloudnative/ with kubernetes-sigs/

### LINKED ISSUE #64: Update documentation after repo migration
Update all docs and replace `huawei-cloudnative/cloud-provider-huaweicloud` with `kubernetes-sigs/cloud-provider-huaweicloud`

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #64 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
/hold 
for CI debug

**Comment by RainbowMango** [comment]
hi, @nikhita are you the owner of `kubernetes-sigs`? 

It seems we need active Travis CI access for this repo.
The job is running on Travis but it can't reflect result to PR.
https://travis-ci.org/github/kubernetes-sigs/cloud-provider-huaweicloud

**Comment by nikhita** [comment]
> hi, @nikhita are you the owner of kubernetes-sigs?

Yep!

> It seems we need active Travis CI access for this repo.
The job is running on Travis but it can't reflect result to PR.

Travis is enabled for the whole org and I can see the travis result on this PR. What am I missing? :)

**Comment by RainbowMango** [comment]
Wow, I can see the travis result now! Maybe it'll take some time to show this result.
Anyway, thanks @nikhita . :)

/hold cancel

**Pull request merged**
