### PR TITLE
remove Config and use ConfigCloud instead in NAT and ELB services

### PR DESCRIPTION
**Pull request by chengxiangdong**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chengxiangdong** [comment]
/retitle remove Config and use ConfigCloud instead in NAT and ELB services

**Comment by niuzhenguo** [comment]
@chengxiangdong needs to resolve the conflicts.

**Pull request merged**
