### PR TITLE
fix logic issue in alb

### PR DESCRIPTION
**Pull request by niuzhenguo**
This fixes the logic of setting EPS id.

**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chengxiangdong** [comment]
`.sw` files do not need to be committed

**Comment by niuzhenguo** [comment]
> `.sw` files do not need to be committed

will add vim related files to gitignore in a following up patch

**Pull request merged**
